// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  tutorialSidebar: [
    {
      type: 'autogenerated',
      dirName: '.',  // Ensure this matches your docs folder structure
    },
    // Example manual sidebar entry (uncomment and modify if needed)
    // {
    //   type: 'link',
    //   label: 'Rain Examples',
    //   href: 'https://rain-examples.unegma.work/',
    // },
  ],

  // Example manual sidebar
  /*
  tutorialSidebar: [
    {
      type: 'category',
      label: 'Tutorial',
      items: ['hello'],
    },
  ],
  */
};

module.exports = sidebars;
